### ISSUE TITLE
GumgaError não funciona junto com datepicker

### ISSUE THREAD

**Issue by igorsantana** [GUMGA/components#91]
Quando adicionada a directive GumgaError junto com datepicker do ui.bootstrap, ela não dá load no formulário inteiro. Isto é causado pois as duas directives estão criando um novo $scope. É desejável que  directives de atributo da Gumga **NÃO** criem um escopo novo, para poder interagir com directives mais complexas.
Erro:

```
Error: [$compile:multidir] http://errors.angularjs.org/1.4.5/$compile/multidir?p0=datepickerPopup&p1=&…sueDate%22%20init-date%3D%22lastUpdate%22%20min-date%3D%22lastUpdate%22%3E
    at Error (native)
    at http://0.0.0.0:8081/bower_components/angular/angular.min.js:6:416
    at N (http://0.0.0.0:8081/bower_components/angular/angular.min.js:69:305)
    at C (http://0.0.0.0:8081/bower_components/angular/angular.min.js:62:443)
    at S (http://0.0.0.0:8081/bower_components/angular/angular.min.js:54:463)
    at S (http://0.0.0.0:8081/bower_components/angular/angular.min.js:55:86)
    at S (http://0.0.0.0:8081/bower_components/angular/angular.min.js:55:86)
    at S (http://0.0.0.0:8081/bower_components/angular/angular.min.js:55:86)
    at S (http://0.0.0.0:8081/bower_components/angular/angular.min.js:55:86)
    at S (http://0.0.0.0:8081/bower_components/angular/angular.min.js:55:86)
```

**Comment by igorsantana** [comment]
O erro foi corrigido, agora a directive gumgaError não cria outro $scope.
